package com.wrk.shopsystem.base.mapper;

import com.wrk.shopsystem.base.model.SalesOrder;
import com.wrk.shopsystem.base.model.SalesOrderExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SalesOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(SalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(SalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(SalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(SalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<SalesOrder> selectByExample(SalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    SalesOrder selectByPrimaryKey(Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") SalesOrder record, @Param("example") SalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") SalesOrder record, @Param("example") SalesOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKeySelective(SalesOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKey(SalesOrder record);
}