spring:
  datasource:
    username: #数据库用户名
    password: #数据库密码
    url: #url
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  security:
    user:
      password: 12345
  mvc:
    static-path-pattern: classpath:/static/**
  redis:

    host:  # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    connect-timeout: 3000ms #超时时间
mybatis:
  mapper-locations:
    - classpath:mapping/*.xml
    - classpath:dao/*.xml
  type-aliases-package: com.zxy.shopsystemdemo.model
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /monitor
server:
  port: 80
logging:
  level:
  - com.zxy.shopsystemdemo.dao: debug
  - com.zxy.shopsystemdemo.mapper: debug
  file:
    path: classpath:logback.xml

