package com.zxy.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table commodity
 */
public class Commodity implements Serializable {
    private Integer cno;

    private String name;

    private Integer commodityTypeNo;

    private Integer supplierNo;

    private Integer colorNo;

    private String barcode;

    private Integer costprice;

    private Integer sellprice;

    private Integer materialType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.cno
     *
     * @return the value of commodity.cno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.cno
     *
     * @param cno the value for commodity.cno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.name
     *
     * @return the value of commodity.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.name
     *
     * @param name the value for commodity.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity_type_no
     *
     * @return the value of commodity.commodity_type_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCommodityTypeNo() {
        return commodityTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity_type_no
     *
     * @param commodityTypeNo the value for commodity.commodity_type_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCommodityTypeNo(Integer commodityTypeNo) {
        this.commodityTypeNo = commodityTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.supplier_no
     *
     * @return the value of commodity.supplier_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getSupplierNo() {
        return supplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.supplier_no
     *
     * @param supplierNo the value for commodity.supplier_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setSupplierNo(Integer supplierNo) {
        this.supplierNo = supplierNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.color_no
     *
     * @return the value of commodity.color_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getColorNo() {
        return colorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.color_no
     *
     * @param colorNo the value for commodity.color_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setColorNo(Integer colorNo) {
        this.colorNo = colorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.barcode
     *
     * @return the value of commodity.barcode
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.barcode
     *
     * @param barcode the value for commodity.barcode
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.costprice
     *
     * @return the value of commodity.costprice
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.costprice
     *
     * @param costprice the value for commodity.costprice
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCostprice(Integer costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.sellprice
     *
     * @return the value of commodity.sellprice
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getSellprice() {
        return sellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.sellprice
     *
     * @param sellprice the value for commodity.sellprice
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setSellprice(Integer sellprice) {
        this.sellprice = sellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.material_type
     *
     * @return the value of commodity.material_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.material_type
     *
     * @param materialType the value for commodity.material_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setMaterialType(Integer materialType) {
        this.materialType = materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cno=").append(cno);
        sb.append(", name=").append(name);
        sb.append(", commodityTypeNo=").append(commodityTypeNo);
        sb.append(", supplierNo=").append(supplierNo);
        sb.append(", colorNo=").append(colorNo);
        sb.append(", barcode=").append(barcode);
        sb.append(", costprice=").append(costprice);
        sb.append(", sellprice=").append(sellprice);
        sb.append(", materialType=").append(materialType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}