package com.zxy.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table purchase_form
 */
public class PurchaseForm implements Serializable {
    private Integer id;

    @ApiModelProperty(value = "所对应进货单（purchase_order的主键）的编号")
    private Integer pid;

    @ApiModelProperty(value = "商品名")
    private Integer commodityId;

    @ApiModelProperty(value = "数量")
    private Integer number;

    private Integer dno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_form.id
     *
     * @return the value of purchase_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_form.id
     *
     * @param id the value for purchase_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_form.pid
     *
     * @return the value of purchase_form.pid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_form.pid
     *
     * @param pid the value for purchase_form.pid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_form.commodity_id
     *
     * @return the value of purchase_form.commodity_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_form.commodity_id
     *
     * @param commodityId the value for purchase_form.commodity_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_form.number
     *
     * @return the value of purchase_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_form.number
     *
     * @param number the value for purchase_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_form.dno
     *
     * @return the value of purchase_form.dno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getDno() {
        return dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_form.dno
     *
     * @param dno the value for purchase_form.dno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setDno(Integer dno) {
        this.dno = dno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pid=").append(pid);
        sb.append(", commodityId=").append(commodityId);
        sb.append(", number=").append(number);
        sb.append(", dno=").append(dno);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}