package com.zxy.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sales_form
 */
public class SalesForm implements Serializable {
    private Integer id;

    private Integer sno;

    private Integer commodityNo;

    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_form.id
     *
     * @return the value of sales_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_form.id
     *
     * @param id the value for sales_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_form.sno
     *
     * @return the value of sales_form.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_form.sno
     *
     * @param sno the value for sales_form.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_form.commodity_no
     *
     * @return the value of sales_form.commodity_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCommodityNo() {
        return commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_form.commodity_no
     *
     * @param commodityNo the value for sales_form.commodity_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCommodityNo(Integer commodityNo) {
        this.commodityNo = commodityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_form.number
     *
     * @return the value of sales_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_form.number
     *
     * @param number the value for sales_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sno=").append(sno);
        sb.append(", commodityNo=").append(commodityNo);
        sb.append(", number=").append(number);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}