package com.zxy.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tranfer_form
 */
public class TranferForm implements Serializable {
    private Integer id;

    private Integer tno;

    private Integer cno;

    private Integer number;

    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranfer_form.id
     *
     * @return the value of tranfer_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranfer_form.id
     *
     * @param id the value for tranfer_form.id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranfer_form.tno
     *
     * @return the value of tranfer_form.tno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranfer_form.tno
     *
     * @param tno the value for tranfer_form.tno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranfer_form.cno
     *
     * @return the value of tranfer_form.cno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranfer_form.cno
     *
     * @param cno the value for tranfer_form.cno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCno(Integer cno) {
        this.cno = cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranfer_form.number
     *
     * @return the value of tranfer_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranfer_form.number
     *
     * @param number the value for tranfer_form.number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tranfer_form.notes
     *
     * @return the value of tranfer_form.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tranfer_form.notes
     *
     * @param notes the value for tranfer_form.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tno=").append(tno);
        sb.append(", cno=").append(cno);
        sb.append(", number=").append(number);
        sb.append(", notes=").append(notes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}