package com.wrk.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table department
 */
public class Department implements Serializable {
    private Integer no;

    private String name;

    private Integer fatherNo;

    private String address;

    private String notes;

    private Integer directorNo;

    private Integer typeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.no
     *
     * @return the value of department.no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.no
     *
     * @param no the value for department.no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.name
     *
     * @return the value of department.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.name
     *
     * @param name the value for department.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.father_no
     *
     * @return the value of department.father_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getFatherNo() {
        return fatherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.father_no
     *
     * @param fatherNo the value for department.father_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setFatherNo(Integer fatherNo) {
        this.fatherNo = fatherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.address
     *
     * @return the value of department.address
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.address
     *
     * @param address the value for department.address
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.notes
     *
     * @return the value of department.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.notes
     *
     * @param notes the value for department.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.director_no
     *
     * @return the value of department.director_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getDirectorNo() {
        return directorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.director_no
     *
     * @param directorNo the value for department.director_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setDirectorNo(Integer directorNo) {
        this.directorNo = directorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.type_no
     *
     * @return the value of department.type_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getTypeNo() {
        return typeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.type_no
     *
     * @param typeNo the value for department.type_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setTypeNo(Integer typeNo) {
        this.typeNo = typeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", no=").append(no);
        sb.append(", name=").append(name);
        sb.append(", fatherNo=").append(fatherNo);
        sb.append(", address=").append(address);
        sb.append(", notes=").append(notes);
        sb.append(", directorNo=").append(directorNo);
        sb.append(", typeNo=").append(typeNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}