package com.wrk.shopsystem.base.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sales_order
 */
public class SalesOrder implements Serializable {
    @ApiModelProperty(value = "零售单号")
    private Integer sno;

    @ApiModelProperty(value = "售出时间")
    private Date time;

    @ApiModelProperty(value = "经手售货员的编号")
    private Integer operNo;

    @ApiModelProperty(value = "顾客编号")
    private Integer customerId;

    @ApiModelProperty(value = "出售门店的编号")
    private Integer shopNo;

    private Byte valid;

    @ApiModelProperty(value = "备注")
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.sno
     *
     * @return the value of sales_order.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.sno
     *
     * @param sno the value for sales_order.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.time
     *
     * @return the value of sales_order.time
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.time
     *
     * @param time the value for sales_order.time
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.oper_no
     *
     * @return the value of sales_order.oper_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getOperNo() {
        return operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.oper_no
     *
     * @param operNo the value for sales_order.oper_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setOperNo(Integer operNo) {
        this.operNo = operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.customer_id
     *
     * @return the value of sales_order.customer_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.customer_id
     *
     * @param customerId the value for sales_order.customer_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.shop_no
     *
     * @return the value of sales_order.shop_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getShopNo() {
        return shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.shop_no
     *
     * @param shopNo the value for sales_order.shop_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setShopNo(Integer shopNo) {
        this.shopNo = shopNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.valid
     *
     * @return the value of sales_order.valid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Byte getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.valid
     *
     * @param valid the value for sales_order.valid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setValid(Byte valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.note
     *
     * @return the value of sales_order.note
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.note
     *
     * @param note the value for sales_order.note
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sno=").append(sno);
        sb.append(", time=").append(time);
        sb.append(", operNo=").append(operNo);
        sb.append(", customerId=").append(customerId);
        sb.append(", shopNo=").append(shopNo);
        sb.append(", valid=").append(valid);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}