spring:
  datasource:
    username: henry
    password: djd2j31rfs
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.203.154:3306/shop?useUnicode=true&characterEncoding=utf8

  redis:
    host: 116.62.203.154 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: d4bff2b06026284a51902247a21a2e026393f446212690c10c1ef86512dd12d1 # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    connect-timeout: 3000ms #超时时间