package com.zxy.shopsystem.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table purchase_order
 */
public class PurchaseOrder implements Serializable {
    private Integer pid;

    @ApiModelProperty(value = "进货备注（必填项）")
    private String pnotes;

    @ApiModelProperty(value = "操作时间")
    private Date orderDate;

    @ApiModelProperty(value = "采购职员id")
    private Integer operEmployeeNo;

    @ApiModelProperty(value = "是否查验")
    private Byte ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table purchase_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.pid
     *
     * @return the value of purchase_order.pid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.pid
     *
     * @param pid the value for purchase_order.pid
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.pnotes
     *
     * @return the value of purchase_order.pnotes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getPnotes() {
        return pnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.pnotes
     *
     * @param pnotes the value for purchase_order.pnotes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setPnotes(String pnotes) {
        this.pnotes = pnotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.order_date
     *
     * @return the value of purchase_order.order_date
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.order_date
     *
     * @param orderDate the value for purchase_order.order_date
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.oper_employee_no
     *
     * @return the value of purchase_order.oper_employee_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getOperEmployeeNo() {
        return operEmployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.oper_employee_no
     *
     * @param operEmployeeNo the value for purchase_order.oper_employee_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setOperEmployeeNo(Integer operEmployeeNo) {
        this.operEmployeeNo = operEmployeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order.ischeck
     *
     * @return the value of purchase_order.ischeck
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Byte getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order.ischeck
     *
     * @param ischeck the value for purchase_order.ischeck
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setIscheck(Byte ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", pnotes=").append(pnotes);
        sb.append(", orderDate=").append(orderDate);
        sb.append(", operEmployeeNo=").append(operEmployeeNo);
        sb.append(", ischeck=").append(ischeck);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}