package com.zxy.shopsystem.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table supplier
 */
public class Supplier implements Serializable {
    private Integer sno;

    private String name;

    private Integer typeId;

    private String address;

    private String phoneNumber;

    private String email;

    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.sno
     *
     * @return the value of supplier.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.sno
     *
     * @param sno the value for supplier.sno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.type_id
     *
     * @return the value of supplier.type_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.type_id
     *
     * @param typeId the value for supplier.type_id
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone_number
     *
     * @return the value of supplier.phone_number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone_number
     *
     * @param phoneNumber the value for supplier.phone_number
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.notes
     *
     * @return the value of supplier.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.notes
     *
     * @param notes the value for supplier.notes
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sno=").append(sno);
        sb.append(", name=").append(name);
        sb.append(", typeId=").append(typeId);
        sb.append(", address=").append(address);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", email=").append(email);
        sb.append(", notes=").append(notes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}