package com.zxy.shopsystem.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table transfer_order
 */
public class TransferOrder implements Serializable {
    private Integer tno;

    private Integer fromNo;

    private Integer destinationNo;

    private Date date;

    private Integer operNo;

    private Byte isfinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table transfer_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.tno
     *
     * @return the value of transfer_order.tno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.tno
     *
     * @param tno the value for transfer_order.tno
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.from_no
     *
     * @return the value of transfer_order.from_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getFromNo() {
        return fromNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.from_no
     *
     * @param fromNo the value for transfer_order.from_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setFromNo(Integer fromNo) {
        this.fromNo = fromNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.destination_no
     *
     * @return the value of transfer_order.destination_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getDestinationNo() {
        return destinationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.destination_no
     *
     * @param destinationNo the value for transfer_order.destination_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setDestinationNo(Integer destinationNo) {
        this.destinationNo = destinationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.date
     *
     * @return the value of transfer_order.date
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.date
     *
     * @param date the value for transfer_order.date
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.oper_no
     *
     * @return the value of transfer_order.oper_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getOperNo() {
        return operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.oper_no
     *
     * @param operNo the value for transfer_order.oper_no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setOperNo(Integer operNo) {
        this.operNo = operNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_order.isfinish
     *
     * @return the value of transfer_order.isfinish
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Byte getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_order.isfinish
     *
     * @param isfinish the value for transfer_order.isfinish
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setIsfinish(Byte isfinish) {
        this.isfinish = isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_order
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tno=").append(tno);
        sb.append(", fromNo=").append(fromNo);
        sb.append(", destinationNo=").append(destinationNo);
        sb.append(", date=").append(date);
        sb.append(", operNo=").append(operNo);
        sb.append(", isfinish=").append(isfinish);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}