package com.zxy.shopsystem.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table worktype
 */
public class Worktype implements Serializable {
    private Integer no;

    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worktype.no
     *
     * @return the value of worktype.no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worktype.no
     *
     * @param no the value for worktype.no
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worktype.name
     *
     * @return the value of worktype.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worktype.name
     *
     * @param name the value for worktype.name
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", no=").append(no);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}