package com.zxy.shopsystem.mapper;

import com.zxy.shopsystem.model.Worktype;
import com.zxy.shopsystem.model.WorktypeExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(WorktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(WorktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(Worktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(Worktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<Worktype> selectByExample(WorktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    Worktype selectByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") Worktype record, @Param("example") WorktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") Worktype record, @Param("example") WorktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKeySelective(Worktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worktype
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKey(Worktype record);
}