package com.zxy.shopsystem.base.mapper;

import com.zxy.shopsystem.base.model.CommodityType;
import com.zxy.shopsystem.base.model.CommodityTypeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommodityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<CommodityType> selectByExample(CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    CommodityType selectByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") CommodityType record, @Param("example") CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") CommodityType record, @Param("example") CommodityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKeySelective(CommodityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_type
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKey(CommodityType record);
}