package com.zxy.shopsystem.base.mapper;

import com.zxy.shopsystem.base.model.CommodityInventory;
import com.zxy.shopsystem.base.model.CommodityInventoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommodityInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(CommodityInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(CommodityInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(CommodityInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(CommodityInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<CommodityInventory> selectByExample(CommodityInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") CommodityInventory record, @Param("example") CommodityInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_inventory
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") CommodityInventory record, @Param("example") CommodityInventoryExample example);
}