package com.zxy.shopsystem.base.mapper;

import com.zxy.shopsystem.base.model.TranferForm;
import com.zxy.shopsystem.base.model.TranferFormExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TranferFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(TranferFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(TranferFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(TranferForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(TranferForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<TranferForm> selectByExample(TranferFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    TranferForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") TranferForm record, @Param("example") TranferFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") TranferForm record, @Param("example") TranferFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKeySelective(TranferForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tranfer_form
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKey(TranferForm record);
}