package com.zxy.shopsystem.base.mapper;

import com.zxy.shopsystem.base.model.UserOperRecord;
import com.zxy.shopsystem.base.model.UserOperRecordExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserOperRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    long countByExample(UserOperRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByExample(UserOperRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insert(UserOperRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int insertSelective(UserOperRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    List<UserOperRecord> selectByExample(UserOperRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    UserOperRecord selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserOperRecord record, @Param("example") UserOperRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByExample(@Param("record") UserOperRecord record, @Param("example") UserOperRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKeySelective(UserOperRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_oper_record
     *
     * @mbg.generated Wed Apr 28 11:02:14 CST 2021
     */
    int updateByPrimaryKey(UserOperRecord record);
}